import json
import os

print("Iniciando o gerador completo de 1.300 questões para as 13 matérias do Ciclo Básico...")

# Define the 13 subjects
SUBJECTS = [
    "Anatomia",
    "Fisiologia",
    "Bioquímica",
    "Histologia",
    "Embriologia",
    "Microbiologia",
    "Imunologia",
    "Genética",
    "Farmacologia",
    "Patologia",
    "Parasitologia",
    "Semiologia",
    "Epidemiologia"
]

# Clinical case intro variations
CLINICAL_INTROS = [
    "Durante discussão de caso clínico em seminário da graduação médica",
    "Em avaliação prática de simulação clínica para estudantes de medicina",
    "Ao examinar prontuário e achados laboratoriais de paciente em investigação",
    "Durante aula prática de bancada e análise de exames complementares",
    "Em estudo dirigido de monitoria acadêmica no módulo de tutoria",
    "Ao analisar laudo de exame complementar e correlacionar com a clínica",
    "Durante atendimento ambulatorial sob supervisão do professor docente",
    "Em reunião de discussão multidisciplinar de casos complexos",
    "Ao avaliar a evolução clínica e os parâmetros fisiopatológicos do paciente",
    "Durante rodízio prático acadêmico no centro de estudos da faculdade"
]

# We build 10 core questions with 10 variations per subject = 100 questions per subject.

def get_clean_subject_id(subject_name):
    clean = subject_name.lower().replace("á", "a").replace("í", "i").replace("ê", "e").replace("ç", "c").replace("ã", "a").replace("é", "e")
    return clean

# Raw Question bank per subject
QUESTION_TEMPLATES = {
    "Anatomia": [
        ("Anatomia Cardiovascular", "Qual artéria corre no sulco interventricular anterior acompanhada pela veia cardíaca magna?",
         ["Artéria coronária direita", "Ramo circunflexo", "Ramo interventricular anterior (descendente anterior)", "Artéria marginal esquerda"], 2,
         "O ramo interventricular anterior da artéria coronária esquerda passa no sulco interventricular anterior acompanhado pela veia cardíaca magna, suprindo a parede anterior do ventrículo esquerdo e 2/3 anteriores do septo interventricular."),
        ("Anatomia Cardiovascular", "A veia ázigo ascende no mediastino posterior e drena diretamente em qual vaso?",
         ["Veia cava superior", "Veia cava inferior", "Átrio direito", "Veia braquiocefálica esquerda"], 0,
         "A veia ázigo faz um arco sobre o brônquio principal direito e desemboca diretamente na face posterior da veia cava superior."),
        ("Anatomia Respiratória", "O brônquio principal direito em relação ao esquerdo é mais propenso a alojar corpos estranhos aspirados por ser:",
         ["Mais longo, estreito e horizontalizado", "Mais curto, largo e verticalizado", "Possuir menor calibração interna", "Possuir menor ângulo em relação à traqueia"], 1,
         "O brônquio principal direito é mais curto, calibroso e verticalizado, facilitando a entrada direta de corpos estranhos aspirados."),
        ("Anatomia Respiratória", "A incisura cardíaca e a lígula pulmonar localizam-se anatômicamente no:",
         ["Lobo superior do pulmão esquerdo", "Lobo inferior do pulmão esquerdo", "Lobo médio do pulmão direito", "Lobo superior do pulmão direito"], 0,
         "A incisura cardíaca acolhe o ápice cardíaco e a lígula é a projeção inferior do lobo superior do pulmão esquerdo."),
        ("Neuroanatomia", "O sulco central do cérebro (sulco de Rolando) divide os giros:",
         ["Giro pré-central e giro pós-central", "Giro frontal superior e médio", "Giro temporal superior e médio", "Giro cingulado e paratrigonal"], 0,
         "O sulco central separa o giro pré-central (Córtex motor primário) do giro pós-central (Córtex somatosensorial primário)."),
        ("Neuroanatomia", "Qual par de nervo craniano emerge da face posterior do tronco encefálico (mesencéfalo)?",
         ["Nervo oculomotor (III)", "Nervo troclear (IV)", "Nervo abducente (VI)", "Nervo trigêmeo (V)"], 1,
         "O nervo troclear (IV par) emerge exclusivamente da superfície posterior (dorsal) do mesencéfalo."),
        ("Neuroanatomia", "O líquido cefalorraquidiano (LCR) é produzido nos ventrículos cerebrais principalmente pelos:",
         ["Plexos coróideos", "Granulações aracnóideas", "Aqueduto cerebral", "Forame de Monro"], 0,
         "Os plexos coróideos, localizados nos ventrículos cerebrais, secretam continuamente o LCR."),
        ("Neuroanatomia", "As granulações aracnóideas reabsorvem o LCR drenando-o diretamente para o:",
         ["Seno sagital superior", "Espaço epidural", "Plexo venoso vertebral", "Sistema linfático cervical"], 0,
         "As granulações aracnóideas drenam o LCR do espaço subaracnóideo para o interior do seno sagital superior da dura-máter."),
        ("Anatomia Abdominal", "A parede posterior do canal inguinal é constituída de forma marcante pela:",
         ["Fáscia transversal e tendão conjunto", "Aponeurose do músculo oblíquo externo", "Músculo reto abdominal", "Músculo iliopsoas"], 0,
         "A fáscia transversal reforçada medialmente pelo tendão conjunto forma a parede posterior do canal inguinal."),
        ("Anatomia Abdominal", "O ligamento hepatoduodenal contendo a tríade portal forma o limite anterior do:",
         ["Forame omental (forame de Winslow)", "Anel inguinal profundo", "Triângulo femoral de Scarpa", "Espaço retroperitoneal"], 0,
         "O limite anterior do forame omental é o ligamento hepatoduodenal, pelo qual passam a veia porta, a artéria hepática própria e o ducto colédoco.")
    ],
    "Fisiologia": [
        ("Fisiologia Renal", "Em qual segmento do néfron ocorre a reabsorção da maior fração do filtrado glomerular (cerca de 65%)?",
         ["Túbulo contorcido distal", "Túbulo contorcido proximal", "Alça de Henle ascendente", "Duto coletor medular"], 1,
         "O túbulo contorcido proximal reabsorve isosmoticamente cerca de 65% da água, sódio, potássio e quase 100% de glicose e aminoácidos."),
        ("Fisiologia Renal", "A vasopressina (ADH) aumenta a reabsorção de água nos dutos coletores renais estimulando a translocação apical de:",
         ["Aquaporina-1", "Aquaporina-2", "Co-transportador Na-K-2Cl", "Bomba Na+/K+ ATPase"], 1,
         "O ADH liga-se aos receptores V2 nos dutos coletores e promove a inserção de canais de água aquaporina-2 na membrana luminal."),
        ("Fisiologia Cardiovascular", "A elevação da força de contração ventricular em resposta ao aumento do volume diastólico final descreve a:",
         ["Lei de Frank-Starling", "Efeito Bowditch", "Reflexo de Bainbridge", "Lei de Poiseuille"], 0,
         "A Lei de Frank-Starling afirma que a força de contração miocárdica aumenta proporcionalmente ao estiramento prévio das fibras (volume diastólico final)."),
        ("Fisiologia Cardiovascular", "A estimulação dos receptores beta-1 adrenérgicos no nó sinoatrial promove principalmente:",
         ["Aumento da frequência cardíaca (cronotropismo positivo)", "Vasodilatação coronariana direta isolada", "Diminuição do inotropismo cardíaco", "Retardo da condução atrioventricular"], 0,
         "A ativação beta-1 no coração aumenta a frequência cardíaca (cronotropismo positivo) e a força contrátil (inotropismo positivo)."),
        ("Fisiologia Respiratória", "O volume de ar inspirado ou expirado em cada respiração normal em repouso denomina-se:",
         ["Volume corrente (VC)", "Volume de reserva inspiratório (VRI)", "Volume residual (VR)", "Capacidade vital (CV)"], 0,
         "O volume corrente (VC) corresponde ao volume de ar mobilizado em cada ciclo respiratório tranquilo (cerca de 500 mL no adulto)."),
        ("Fisiologia Respiratória", "O surfactante pulmonar reduz a tensão superficial nos alvéolos evitando o colapso (atelectasia), sendo produzido pelas células:",
         ["Pneumócitos tipo I", "Pneumócitos tipo II", "Macrófagos alveolares", "Células caliciformes"], 1,
         "Os pneumócitos tipo II sintetizam e secretam o surfactante pulmonar (rico em dipalmitoilfostatidilcolina)."),
        ("Fisiologia Endócrina", "A secreção do hormônio hipotireoidiano (PTH) pelas paratireoides é estimulada primariamente por:",
         ["Redução da concentração de cálcio iônico plasmático", "Elevação da calcitonina", "Elevação do cálcio plasmático", "Inibição da vitamina D"], 0,
         "A hipocalcemia (baixa de Ca2+ iônico no plasma) estimula diretamente as glândulas paratireoides a secretarem PTH."),
        ("Fisiologia Endócrina", "A insulina promove o ingresso de glicose nas células musculares e adiposas mediante translocação do transportador:",
         ["GLUT-1", "GLUT-2", "GLUT-4", "SGLT-2"], 2,
         "O GLUT-4 é o transportador de glicose dependente de insulina expresso no tecido muscular esquelético/cardíaco e tecido adiposo."),
        ("Neurofisiologia", "A fase de despolarização rápida do potencial de ação neuronal decorre da abertura de canais dependentes de voltagem de:",
         ["Sódio (Na+)", "Potássio (K+)", "Cálcio (Ca2+)", "Cloro (Cl-)"], 0,
         "A entrada maciça e rápida de íons Na+ através de canais de Na+ voltagem-dependentes provoca a despolarização do potencial de membrana."),
        ("Fisiologia Gastrintestinal", "Qual hormônio secretado pelas células S do duodeno estimula a secreção pancreática rica em bicarbonato?",
         ["Gastrina", "Secretina", "Colecistococina (CCK)", "Peptídeo Inibidor Gástrico (GIP)"], 1,
         "A secretina é liberada pela chegada do quimo ácido ao duodeno e estimula o pâncreas exócrino a secretar água e bicarbonato.")
    ],
    "Bioquímica": [
        ("Metabolismo de Carboidratos", "Qual enzima atua como o principal ponto de regulação alostérica da via glicolítica, inibida por ATP e ativada por AMP?",
         ["Hexocinase", "Fosfofrutocinase-1 (PFK-1)", "Piruvato quinase", "Glicose-6-fosfatase"], 1,
         "A PFK-1 é a enzima marca-passo e ponto chave de regulação alostérica da glicólise."),
        ("Metabolismo de Carboidratos", "A via de síntese de glicose a partir de precursores não glicídicos (lactato, glicerol, alanina) durante o jejum é a:",
         ["Glicogênese", "Gliconeogênese", "Via das Pentoses Fosfato", "Ciclo da Ureia"], 1,
         "A gliconeogênese produz glicose nova no fígado e rins para manter a glicemia durante períodos de jejum."),
        ("Cadeia Respiratória", "O complexo IV da cadeia de transporte de elétrons mitocondrial transfere elétrons diretamente para qual aceptor final?",
         ["NADH", "Oxigênio molecular (O2)", "Coenzima Q (Ubiquinona)", "Citocromo c"], 1,
         "O complexo IV (citocromo c oxidase) transfere elétrons para o O2, reduzindo-o a água H2O."),
        ("Metabolismo de Lipídios", "A beta-oxidação dos ácidos graxos ocorre no interior de qual organela celular?",
         ["Mitocôndria (matriz mitocondrial)", "Retículo endoplasmático liso", "Complexo de Golgi", "Lisossomo"], 0,
         "Os ácidos graxos ativados entram na matriz mitocondrial via lançadeira de carnitina e passam pela beta-oxidação."),
        ("Metabolismo de Lipídios", "Qual lipoproteína é responsável pelo transporte reverso do colesterol dos tecidos periféricos para o fígado?",
         ["VLDL", "LDL", "HDL", "Quilomícron"], 2,
         "O HDL realiza o transporte reverso do colesterol, retirando excesso de colesterol dos tecidos e vasos para depuração hepática."),
        ("Metabolismo de Proteínas", "O ciclo da ureia ocorre no fígado para excretar a amônia tóxica, sendo sua primeira enzima mitocondrial a:",
         ["Carbamil-fosfato sintetase I (CPS-I)", "Ornitina transcarbamilase", "Argininosuccinato sintetase", "Arginase"], 0,
         "A CPS-I condensa amônia e bicarbonato em carbamil-fosfato na matriz mitocondrial hepática."),
        ("Enzimologia", "Um inibidor competitivo de uma reação enzimática altera os parâmetros cinéticos de Michaelis-Menten de qual forma?",
         ["Aumenta o Km aparente mantendo a Vmax inalterada", "Diminui a Vmax mantendo o Km inalterado", "Diminui tanto o Km quanto a Vmax", "Aumenta a Vmax e diminui o Km"], 0,
         "Inibidores competitivos competem pelo sítio ativo com o substrato, aumentando o Km aparente sem alterar a Vmax."),
        ("Via das Pentoses", "A via das pentoses fosfato gera NADPH fundamental para a síntese lipídica e defesa antioxidante através da enzima chave:",
         ["Glicose-6-fosfato desidrogenase (G6PD)", "Transcetolase", "Aldolase B", "Frutocinase"], 0,
         "A G6PD catalisa o passo limitante da via das pentoses, gerando NADPH essencial para a glutationa redutase."),
        ("Integração Metabólica", "No estado de jejum prolongado, o cérebro adapta-se para utilizar como fonte alternativa de energia os:",
         ["Corpos cetônicos (acetoacetato e beta-hidroxibutirato)", "Ácidos graxos livres de cadeia longa", "Aminoácidos ramificados intactos", "Triglicerídeos plasmáticos"], 0,
         "Corpos cetônicos sintetizados pelo fígado atravessam a barreira hematoencefálica e suprem até 70% das necessidades energéticas do cérebro no jejum."),
        ("Metabolismo de Glicogênio", "A quebra do glicogênio hepático (glicogenólise) é ativada no jejum por fosforilação da glicogênio fosforilase sob ação do:",
         ["Glucagon e Adrenalina", "Insulina", "Cortisol", "Hormônio do Crescimento (GH)"], 0,
         "O glucagon (no fígado) e a adrenalina (no músculo) ativam a cascata do AMPc/PKA, ativando a glicogênio fosforilase.")
    ],
    "Histologia": [
        ("Tecido Epitelial", "O epitélio de revestimento da traqueia e brônquios principais é classificado histologicamente como:",
         ["Epitélio estratificado pavimentoso não queratinizado", "Epitélio pseudoestratificado cilíndrico ciliado com células caliciformes", "Epitélio simples cúbico com microvilosidades", "Epitélio de transição (urotélio)"], 1,
         "O aparelho respiratório de condução é revestido por epitélio pseudoestratificado cilíndrico ciliado rico em células caliciformes produtoras de muco."),
        ("Tecido Epitelial", "Qual junção celular de ancoragem conecta o citoesqueleto de filamentos intermediários da célula epitelial à lâmina basal?",
         ["Desmossomo (macula adherens)", "Hemidesmossomo", "Junção comunicante (gap)", "Zônula de oclusão"], 1,
         "Os hemidesmossomos ancoram a membrana plasmática basal das células epiteliais à lâmina basal subjacente por meio de integrinas."),
        ("Tecido Conjuntivo", "A célula do tecido conjuntivo propriamente dito responsável pela síntese do colágeno, elastina e matriz extracelular é o:",
         ["Fibroblasto", "Macrófago", "Mastócito", "Plasmócito"], 0,
         "O fibroblasto é a célula principal e mais abundante do tecido conjuntivo, sintetizando a matriz extracelular e as fibras."),
        ("Tecido Ósseo", "A célula multinucleada derivada da linhagem monocítica responsável pela reabsorção da matriz óssea é o:",
         ["Osteoblasto", "Osteócito", "Osteoclasto", "Osteoprogenitora"], 2,
         "Os osteoclastos são células multinucleadas gigantes especializadas na reabsorção óssea pela secreção de ácidos e proteases."),
        ("Tecido Muscular", "No sarcômero do músculo estriado esquelético, os filamentos finos são compostos predominantemente por:",
         ["Miosina", "Actina, tropomiosina e troponina", "Titina e nebulina", "Desmina"], 1,
         "Os filamentos finos são constituídos por polímeros de actina F associados ao complexo regulador de tropomiosina e troponinas (TnI, TnT, TnC)."),
        ("Tecido Nervoso", "As células da glia responsáveis pela formação da bainha de mielina no Sistema Nervoso Central (SNC) são os:",
         ["Oligodendrócitos", "Células de Schwann", "Astrócitos", "Micróglia"], 0,
         "Os oligodendrócitos mielinizam múltiplos axônios no SNC, enquanto as células de Schwann mielinizam no SNP."),
        ("Sangue", "A célula sanguínea anucleada em forma de disco bicôncavo rica em hemoglobina é o:",
         ["Eritrócito (hemácia)", "Plaqueta (trombócito)", "Neutrófilo", "Linfócito"], 0,
         "Os eritrócitos maduros no sangue periférico humano são anucleados e otimizados para o transporte de O2 e CO2."),
        ("Órgãos Linfoides", "A polpa vermelha do baço desempenha principalmente a função de:",
         ["Filtragem sanguínea e remoção de eritrócitos senescentes (hemocaterese)", "Apresentação de antígenos por células dendríticas tímicas", "Produção de imunoglobulina A secretora", "Maturação de linfócitos T"], 0,
         "A polpa vermelha esplênica é formada por sinusóides venosos e cordões de Billroth, atuando na hemocaterese."),
        ("Pele e Anexos", "A camada mais superficial da epiderme constituída por células mortas anucleadas repleta de queratina é o:",
         ["Estrato basal", "Estrato espinhoso", "Estrato granuloso", "Estrato córneo"], 3,
         "O estrato córneo é composto por camadas de corneócitos mortos e descamativos achatados impregnados de queratina."),
        ("Sistema Renal", "Os podócitos com seus pedicelos interdigitados compõem o folheto visceral da cápsula de Bowman revestindo os capilares do:",
         ["Glomérulo renal", "Túbulo contorcido proximal", "Alça de Henle", "Duto coletor"], 0,
         "Os podócitos revestem externamente os capilares fenestrados do glomérulo renal, formando fendas de filtração.")
    ],
    "Embriologia": [
        ("Primeira Semana", "A implantação do blastocisto (nidação) no endométrio uterino ocorre normalmente cerca de quantos dias pós-fecundação?",
         ["1 a 2 dias", "6 a 7 dias", "14 dias", "21 dias"], 1,
         "A nidação inicia-se por volta do 6º ao 7º dia após a fertilização com a adesão do trofoblasto ao endométrio receptivo."),
        ("Folhetos Germinativos", "A gastrulação marca o início da morfogênese embrionária com a formação da linha primitiva e estabelecimento dos:",
         ["Três folhetos germinativos (ectoderma, mesoderma e endoderma)", "Anexos placentários maduros", "Quatro cavidades cardíacas", "Gânglios da raiz dorsal"], 0,
         "A gastrulação converte o disco embrionário bilaminar em trilaminar (ectoderma, mesoderma e endoderma)."),
        ("Neurulação", "As células da crista neural migram pelo corpo do embrião dando origem a qual conjunto de estruturas?",
         ["Gânglios sensitivos e autônomos, melanócitos e medula supra-renal", "Eritrócitos e miocárdio", "Fígado e pâncreas", "Músculo reto abdominal"], 0,
         "A crista neural origina os gânglios nervosos periféricos, células de Schwann, melanócitos, esqueleto crânio-facial e medula adrenal."),
        ("Cardiovascular Embrionário", "O desvio de sangue oxigenado da placenta no feto diretamente do átrio direito para o átrio esquerdo ocorre pelo:",
         ["Forame oval (fossa oval pós-natal)", "Ducto arterioso (canal arterial)", "Ducto venoso", "Ventriculostomia"], 0,
         "O forame oval permite a passagem do sangue bem oxigenado do átrio direito diretamente para o átrio esquerdo no feto."),
        ("Circulação Fetal", "O ducto venoso na circulação fetal conecta a veia umbilical diretamente à:",
         ["Veia cava inferior", "Veia porta", "Veia cava superior", "Artéria pulmonar"], 0,
         "O ducto venoso desvia o sangue oxigenado vindo da veia umbilical ultrapassando o sinusóide hepático para a veia cava inferior."),
        ("Aparelho Faríngeo", "O primeiro arco faríngeo (arco mandibular) é inervado por qual nervo craniano?",
         ["Nervo trigêmeo (V par - ramo mandibular V3)", "Nervo facial (VII par)", "Nervo glossofaríngeo (IX par)", "Nervo vago (X par)"], 0,
         "O 1º arco faríngeo é inervado pelo nervo trigêmeo (V3) e origina a mandíbula, maxila, martelo e bigorna."),
        ("Malformações Congênitas", "A falha de fechamento do neuroporo posterior ao final da quarta semana embrionária resulta em:",
         ["Espinha bífida (defeitos do tubo neural)", "Anencefalia", "Lábio leporino", "Atresia esofágica"], 0,
         "O não fechamento do neuroporo posterior gera defeitos de fechamento do arco vertebral e tubo neural (espinha bífida)."),
        ("Placentação", "O sinciciotrofoblasto erode os vasos endometriais maternos e secreta o hormônio indicador de gravidez precoce:",
         ["Gonadotrofina coriônica humana (hCG)", "Progesterona placentária", "Lactogênio placentário", "Estradiol"], 0,
         "O sinciciotrofoblasto produz hCG para manter o corpo lúteo no início da gestação."),
        ("Digestório Embrionário", "A persistência do ducto onfalomesentérico (vitelino) pode originar no íleo terminal a malformação de:",
         ["Divertículo de Meckel", "Megacólon congênito (Hirschsprung)", "Estenose hipertrófica do piloro", "Volvo intestinal"], 0,
         "O divertículo de Meckel é um resquício do ducto vitelino localizado na borda antimesentérica do íleo."),
        ("Urogenital Embrionário", "O sistema renal definitivo humano desenvolve-se a partir de qual estrutura primórdio embrionária?",
         ["Metanefro e broto ureteric", "Pronefro", "Mesonefro funcional", "Saco vitelino"], 0,
         "O rim definitivo (metanefro) origina-se da interação entre o broto ureterórico e o blastema metanéfrico.")
    ],
    "Microbiologia": [
        ("Bacteriologia", "Cocos Gram-positivos dispostos em cadeias, beta-hemolíticos e sensíveis à bacitracina (Grupo A de Lancefield) correspondem a:",
         ["Streptococcus pyogenes", "Streptococcus pneumoniae", "Staphylococcus aureus", "Enterococcus faecalis"], 0,
         "O Streptococcus pyogenes (Strepto do Grupo A) é beta-hemolítico e sensível à bacitracina."),
        ("Bacteriologia", "Qual bactéria Gram-negativa em forma de vírgula, oxidase positiva, causa diarreia profusa em 'água de arroz' por toxina que ativa o AMPc?",
         ["Vibrio cholerae", "Escherichia coli enterohemorrágica", "Salmonella enterica", "Shigella dysenteriae"], 0,
         "O Vibrio cholerae produz a toxina colérica que hiperativa a adenilato ciclase no enterócito, gerando diarreia maciça."),
        ("Virologia", "Qual vírus hepatotrópico de genoma DNA de fita dupla parcial possui envelope contendo o antígeno de superfície HBsAg?",
         ["Vírus da Hepatite B (HBV)", "Vírus da Hepatite A (HAV)", "Vírus da Hepatite C (HCV)", "Vírus da Hepatite E (HEV)"], 0,
         "O HBV é o único vírus da hepatite humana com genoma DNA e possui os antígenos HBsAg, HBcAg e HBeAg."),
        ("Micologia", "A levedura encapsulada oportunista causadora de meningite em imunodeprimidos identificada na tinta da China (nanquim) é:",
         ["Cryptococcus neoformans", "Candida albicans", "Aspergillus fumigatus", "Histoplasma capsulatum"], 0,
         "O Cryptococcus neoformans possui espessa cápsula polissacarídica evidenciada negativamente pela Coloração com Tinta da China."),
        ("Antimicrobianos", "Os antibióticos beta-lactâmicos (penicilinas, cefalosporinas e carbapenêmicos) exercem ação bactericida inibindo a:",
         ["Síntese da parede celular bacteriana (transpeptidação do peptidoglicano)", "Subunidade 30S do ribossomo", "DNA girase (Topoisomerase II)", "RNA polimerase dependente de DNA"], 0,
         "Os beta-lactâmicos ligam-se às PBPs (Penicillin-Binding Proteins) e bloqueiam a ligação cruzada de peptidoglicano na parede celular."),
        ("Antimicrobianos", "A resistência bacteriana à vancomicina em cepas de Enterococcus (VRE) decorre da modificação do dipeptídeo da parede de D-Ala-D-Ala para:",
         ["D-Alanina-D-Lactato", "D-Glutato-D-Alanina", "L-Lisina-D-Ala", "Glicina-Glicina"], 0,
         "O operon vanA/vanB altera o alvo de ligação da vancomicina para D-Ala-D-Lactato, reduzindo a afinidade da droga."),
        ("Bacteriologia", "O bacilo Gram-positivo aeróbico estrito com parede rica em ácidos micólicos resistente à descoloração por álcool-ácido (BAAR) é o:",
         ["Mycobacterium tuberculosis", "Listeria monocytogenes", "Corynebacterium diphtheriae", "Bacillus anthracis"], 0,
         "Os bacilos álcool-ácido resistentes (BAAR), como M. tuberculosis, coram-se pela técnica de Ziehl-Neelsen devido à alta concentração de ácidos micólicos."),
        ("Virologia", "O vírus influenza modifica ciclicamente seus antígenos de superfície Hemaglutinina (HA) e Neuraminidase (NA) através do fenômeno de recombinação genética denominado:",
         ["Drift e Shift antigênico", "Lisogenia", "Transformação bacteriana", "Transdução generalizada"], 0,
         "Alterações menores por mutações ponto (drift) causam surtos anuais, enquanto grandes rearranjos de segmentos genômicos (shift) geram pandemias."),
        ("Micologia", "O fungo dimórfico endêmico no Brasil associado ao contato com solo e vegetação com aspecto de 'roda de leme' no exame direto é:",
         ["Paracoccidioides brasiliensis", "Sporothrix schenckii", "Blastomyces dermatitidis", "Coccidioides immitis"], 0,
         "O Paracoccidioides brasiliensis exibe no tecido a forma leveduriforme multibrotante característica de 'roda de leme'."),
        ("Diagnóstico Microbiológico", "A fermentação da lactose no meio ágar MacConkey permite diferenciar enterobactérias produtoras de colônias rosadas como a:",
         ["Escherichia coli", "Salmonella typhi", "Shigella flexneri", "Pseudomonas aeruginosa"], 0,
         "E. coli e Klebsiella são bacilos Gram-negativos lactose-positivos (fermentadores de lactose), formando colônias rosa/vermelhas em ágar MacConkey.")
    ],
    "Imunologia": [
        ("Imunidade Inata", "Os receptores de reconhecimento de padrão (PRRs), como os Toll-like Receptors (TLRs), reconhecem nas superfícies microbianas os:",
         ["Padrões moleculares associados a patógenos (PAMPs)", "Antícorpos IgG autólogos", "Complexos HLA de classe I", "Epitopos de células T ativadas"], 0,
         "PRRs identificam PAMPs (como LPS, flagelina e RNA de fita dupla) conservados evolutivamente em microrganismos."),
        ("Sistema Complemento", "A via alternativa de ativação do sistema complemento é iniciada de forma espontânea pela hidrólise do componente:",
         ["C3", "C1q", "C4", "C5"], 0,
         "A via alternativa é ativada constantemente em baixo nível pelo 'tick-over' espontâneo do C3 em C3(H2O)."),
        ("Apresentação de Antígenos", "As moléculas do Complexo Principal de Histocompatibilidade (MHC) de Classe I apresentam peptídeos endógenos aos linfócitos T:",
         ["T CD8+ citotóxicos", "T CD4+ auxiliares (Th)", "B de memória", "Naturais Killer (NK) de repouso"], 0,
         "MHC de classe I (presente em todas as células nucleadas) apresenta peptídeos aos T CD8+, enquanto MHC II apresenta aos T CD4+."),
        ("Imunoglobulinas", "A imunoglobulina produzida na forma de dímero associada à peça secretora protegendo mucosas respiratórias e digestivas é a:",
         ["IgA", "IgG", "IgM", "IgE"], 0,
         "A IgA secretora é a principal classe de anticorpos presente nas secreções mucosas e leite materno."),
        ("Imunoglobulinas", "A isoforma de imunoglobulina envolvida primariamente na degranulação de mastócitos e basófilos em reações alérgicas é a:",
         ["IgE", "IgM", "IgG4", "IgD"], 0,
         "A IgE liga-se aos receptores Fc-epsilon-RI nos mastócitos, e seu entrecruzamento por alérgenos desencadeia anafilaxia/alergia."),
        ("Hipersensibilidade", "A reação de hipersensibilidade Tipo II (mediada por anticorpos citotóxicos) é exemplificada clinicamente pela:",
         ["Reação transfusional por incompatibilidade ABO", "Asma brônquica alérgica", "Doença do soro", "Dermatite de contato por níquel"], 0,
         "Na reação tipo II, IgG ou IgM ligam-se a antígenos na superfície celular, ativando complemento e fagocitose (ex: hemólise transfusional)."),
        ("Hipersensibilidade", "A dermatite de contato por hera venenosa ou níquel e a reação à tuberculina (PPD) são reações de hipersensibilidade mediadas por células T do Tipo:",
         ["Tipo IV (tardia)", "Tipo I (imediata)", "Tipo II (citotóxica)", "Tipo III (por imunocomplexos)"], 0,
         "A hipersensibilidade tipo IV é mediada por linfócitos T sensibilizados e macrófagos, sem participação direta de anticorpos solúveis."),
        ("Tolerância Imunológica", "A deleção clonal de linfócitos T autoreativos durante a maturação no timo através do reconhecimento de autoantígenos (proteína AIRE) representa a:",
         ["Tolerância central", "Tolerância periférica por anergia", "Supressão por Treg", "Exaustão clonal"], 0,
         "A tolerância central elimina clones T e B autoreativos nos órgãos linfoides primários (timo e medula óssea)."),
        ("Imunodeficiência", "A Agamaglobulinemia ligada ao X (Síndrome de Bruton) decorre da mutação no gene BTK com ausência de maturação de:",
         ["Linfócitos B", "Linfócitos T CD4+", "Células NK", "Neutrófilos"], 0,
         "A deficiência da tirosina quinase de Bruton (BTK) bloqueia o desenvolvimento de pré-linfócitos B em B maduros, zerando imunoglobulinas."),
        ("Vacinas", "A vacina constituída por microrganismos vivos atenuados contra o sarampo, caxumba e rubéola (Tríplice Viral) estimula de forma marcante a imunidade:",
         ["Celular (T CD8+ e T CD4+) e humoral duradoura", "Apenas humoral passiva transitória", "Exclusivamente barreira inata mucosal", "Apenas ativação de neutrófilos"], 0,
         "Vacinas atenuadas replicam-se discretamente e apresentam antígenos por MHC I e II, gerando imunidade celular e humoral robusta.")
    ],
    "Genética": [
        ("Herança Monogênica", "Um padrão de herança autossômica dominante caracteriza-se na árvore genealógica por afetar:",
         ["Indivíduos de ambas as gerações sucessivas com transmissão de pai para filho", "Exclusivamente homens descendentes de mães portadoras", "Apenas prole de casamentos consanguíneos", "Apenas descendentes por linha materna mitocondrial"], 0,
         "Na herança autossômica dominante, a mutação em um único alelo gera a doença, afetando ambos os sexos e transmitindo-se verticalmente."),
        ("Herança Ligada ao X", "Na herança recessiva ligada ao cromossomo X (ex: Hemofilia A e Distrofia de Duchenne), homens afetados transmitem o alelo mutado para:",
         ["Todas as suas filhas (portadoras) e nenhum dos seus filhos homens", "50% dos seus filhos homens e 50% das filhas", "Todos os seus filhos homens e nenhuma das filhas", "Exclusivamente para os netos homens por linha paterna"], 0,
         "O pai transmite seu único cromossomo X para todas as filhas e o Y para os filhos. Logo, todas as filhas do homem afetado serão portadoras obrigatoriamente."),
        ("Citogenética", "A Síndrome de Down é causada em mais de 95% dos casos por trisomia livre do cromossomo 21 decorrente de:",
         ["Não-disjunção meiótica (predominantemente na meiose I materna)", "Translocação robertsoniana balanceada paterna", "Inversão pericêntrica do cromossomo 21", "Mosaico mitótico embrionário tardio"], 0,
         "A não-disjunção meiótica do par 21 durante a monogênese materna (associada à idade materna avançada) é a causa principal da trissomia do 21."),
        ("Genética Molecular", "O dogma central da biologia molecular descreve o fluxo de informação genética na sequência de:",
         ["Replicação do DNA -> Transcrição para RNA -> Tradução para Proteína", "Tradução de Proteína -> Transcrição para RNA -> DNA", "RNA -> Proteína -> DNA mitocondrial", "Transcrição de Proteína -> Replicação de RNA"], 0,
         "O fluxo genético clássico ocorre do DNA (molde) transcrito em mRNA e traduzido em cadeia polipeptídica nos ribossomos."),
        ("Mutações", "Uma mutação pontual que altera um códon codificador de aminoácido para um códon de parada precoce (UAA, UAG, UGA) é denominada mutação:",
         ["Nonsense (sem sentido)", "Missense (de sentido trocado)", "Silenciosa (sinônima)", "Frameshift (mudança na matriz de leitura)"], 0,
         "Mutações nonsense introduzem prematuramente um códon de terminação, truncando a proteína final."),
        ("Oncogenética", "O gene TP53 é considerado o 'guardião do genoma', atuando como um clássico gene:",
         ["Supressor de tumor (indutor de parada do ciclo celular e apoptose)", "Proto-oncogene ativador de tirosina quinase", "Gene de fusão oncogênico", "Inibidor de reparo por excisão de bases"], 0,
         "O p53 detecta danos no DNA na fase G1/S, ativando reparo ou induzindo apoptose se o dano for irreparável."),
        ("Epigenética", "A inativação aleatória do cromossomo X nas células somáticas femininas formando o corpúsculo de Barr no núcleo interfásico decorre de:",
         ["Metilação do DNA e modificações de histonas pelo RNA XIST", "Deleção completa do braço curto do X", "Duplicação do cromossomo Y", "Acetilação maciça da cromatina"], 0,
         "O lncRNA XIST reveste e silencia epigeneticamente um dos cromossomos X femininos (hipótese de Lyon)."),
        ("Epigenética", "A expressão diferencial de um alelo genético dependendo se ele foi herdado do pai ou da mãe é o fenômeno denominado:",
         ["Imprinting genômico (ex: Síndromes de Prader-Willi e Angelman)", "Penetrância incompleta", "Expressividade variável", "Pleiotropia"], 0,
         "O imprinting genômico silencia epigeneticamente alelos parental-específicos durante a gametogênese."),
        ("Diagnóstico Genético", "A técnica molecular de PCR (Reação em Cadeia da Polimerase) permite:",
         ["Amplificar exponencialmente sequências específicas de DNA in vitro", "Determinar a cariotipagem estrutural em metáfase", "Sequenciar proteínas maduras plasmáticas", "Criar vetores de clonagem de linfócitos B"], 0,
         "A PCR utiliza primers específicos e DNA polimerase termoresistente (Taq) para amplificar trechos alvos de DNA."),
        ("Genética de Populações", "Em uma população no equilíbrio de Hardy-Weinberg com dois alelos (A e a) com frequência de a = 0,2, a frequência de heterozigotos (Aa) é:",
         ["0,32 (32%)", "0,16 (16%)", "0,04 (4%)", "0,64 (64%)"], 0,
         "p + q = 1 -> se q = 0,2, p = 0,8. A frequência de heterozigotos 2pq = 2 x 0,8 x 0,2 = 0,32 (32%).")
    ],
    "Farmacologia": [
        ("Farmacocinética", "A porcentagem de um fármaco administrado que atinge a circulação sistêmica na sua forma inalterada é denominada:",
         ["Biodisponibilidade", "Volume de distribuição", "Clearance de depuração", "Meia-vida de eliminação"], 0,
         "A biodisponibilidade (F) mede a fração da dose administrada que alcança a circulação sistêmica (100% via IV)."),
        ("Farmacocinética", "As reações de Fase I do metabolismo hepático de drogas incluem hidroxilação e oxidação efetuadas pelo complexo enzimático:",
         ["Citocromo P450 (CYP450)", "UDP-glicuronosiltransferase", "Glutationa S-transferase", "Álcool desidrogenase"], 0,
         "O sistema CYP450 hepático catalisa reações de Fase I (oxidação, redução e hidrólise) alterando a polaridade da droga."),
        ("Farmacodinâmica", "Um antagonista competitivo reversível altera a curva dose-resposta de um agonista de qual maneira?",
         ["Desloca a curva para a direita aumentando a EC50 sem alterar o efeito máximo", "Reduz o efeito máximo sem alterar a EC50", "Desloca a curva para a esquerda aumentando a potência", "Aumenta a eficácia máxima do agonista"], 0,
         "O antagonista competitivo compete pelo mesmo sítio do receptor, exigindo maiores concentrações do agonista para alcançar o mesmo efeito."),
        ("Farmacologia do SNA", "A atropina é um fármaco bloqueador competitivo de receptores:",
         ["Muscarínicos da acetilcolina (anticolinérgico)", "Nicotínicos da junção neuromuscular", "Alfa-1 adrenérgicos", "Beta-1 adrenérgicos"], 0,
         "A atropina bloqueia receptores muscarínicos (M1-M5), causando taquicardia, midríase, retenção urinária e xerostomia."),
        ("Farmacologia Cardiovascular", "Os inibidores da Enzima Conversora de Angiotensina (iECA, ex: enalapril) reduzem a pressão arterial e podem causar tosse seca por acúmulo de:",
         ["Bradicinina", "Serotonina", "Histamina", "Endotelina-1"], 0,
         "A ECA também degrada a bradicinina. A inibição da ECA eleva os níveis pulmonares de bradicinina, desencadeando tosse seca."),
        ("Farmacologia Cardiovascular", "Qual diurético inibe o co-transportador Na+/K+/2Cl- no ramo ascendente espesso da alça de Henle, possuindo alta potência natriurética?",
         ["Furosemida (diurético de alça)", "Hidroclorotiazida", "Espironolactona", "Acetazolamida"], 0,
         "A furosemida atua no ramo ascendente da alça de Henle bloqueando o NKCC2, excretando grande volume de Na+, K+, Cl- e água."),
        ("Farmacologia do SNA", "Qual medicação agonista seletivo dos receptores beta-2 adrenérgicos promove broncodilatação rápida nas crises de asma?",
         ["Salbutamol", "Propranolol", "Atenolol", "Pilocarpina"], 0,
         "O salbutamol estimula os receptores beta-2 no músculo liso brônquico, elevando o AMPc e induzindo broncodilatação."),
        ("Anti-inflamatórios", "Os AINEs (como ibuprofeno e cetoprofeno) reduzem dor e inflamação inibindo a enzima:",
         ["Ciclooxigenase (COX-1 e COX-2)", "5-lipoxigenase (5-LOX)", "Fosfolipase A2", "Tromboxano sintetase"], 0,
         "Os AINEs inibem a conversão do ácido araquidônico em prostaglandinas inflamatórias pelas enzimas COX."),
        ("Opioides", "A depressão respiratória aguda por superdosagem de opióides (morfina, fentanil) é revertida prontamente pelo antagonista:",
         ["Naloxona", "Flumazenil", "Atropina", "N-acetilcisteína"], 0,
         "A naloxona é um antagonista puro de receptores opioides mu (µ), revertendo a depressão respiratória."),
        ("Anticoagulantes", "A varfarina exerce seu efeito anticoagulante inibindo a enzima epóxido redutase da vitamina K, bloqueando a síntese dos fatores de coagulação:",
         ["Fatores II, VII, IX e X (dependentes de vitamina K)", "Fatores VIII, V e Fibrinogênio", "Fator XIII e Trombina", "Fator XI e XII"], 0,
         "A varfarina inibe a gama-carboxilação hepática dos fatores II, VII, IX e X de coagulação.")
    ],
    "Patologia": [
        ("Lesão Celular", "A morte celular programada ativamente sem ruptura da membrana plasmática e sem reação inflamatória circundante é a:",
         ["Apoptose", "Necrose de coagulação", "Necrose liquefativa", "Necrose gordurosa"], 0,
         "A apoptose é a morte celular fisiológica ou patológica limpa por condensação de cromatina e corpos apoptóticos sem inflamação."),
        ("Morte Celular", "O tipo de necrose tecidual observada em infartos isquêmicos do miocárdio e rim caracterizada por preservação do contorno celular é a:",
         ["Necrose de coagulação", "Necrose liquefativa", "Necrose caseosa", "Necrose gangrenosa"], 0,
         "A necrose de coagulação preserva o arcabouço tecidual por desnaturação das proteínas estruturais e enzimáticas."),
        ("Morte Celular", "A necrose liquefativa em que o tecido é digerido e transformado em massa fluida viscosa é padrão característico do infarto em qual órgão?",
         ["Cérebro (Sistema Nervoso Central)", "Coração", "Fígado", "Baço"], 0,
         "O infarto cerebral (isquêmico) resulta em necrose liquefativa devido ao alto teor de lipídios e enzimas autolíticas."),
        ("Inflamação", "Os neutrófilos são as primeiras células recrutadas para o sítio da lesão tecidual, sendo o achado histológico marcante da:",
         ["Inflamação aguda", "Inflamação crônica granulomatosa", "Atrofia tecidual", "Metaplasia escamosa"], 0,
         "A inflamação aguda caracteriza-se por exsudação de fluidos e infiltração maciça de polimorfonucleares (neutrófilos)."),
        ("Inflamação Crônica", "O granuloma imune tuberculoso exibe no seu centro um padrão de necrose e é circundado por linfócitos e células epitelióides do tipo:",
         ["Necrose caseosa e células gigantes de Langhans", "Necrose gordurosa e macrófagos xantomatosos", "Necrose fibrinóide e plasmócitos", "Abcesso purulento com neutrófilos"], 0,
         "O granuloma caseoso da tuberculose é formado por macrófagos modificados (células epitelióides), células de Langhans e necrose caseosa."),
        ("Neoplasias", "A substituição reversível de um tipo celular adulto por outro tipo celular adulto mais resistente ao estresse (ex: esôfago de Barrett) denomina-se:",
         ["Metaplasia", "Displasia", "Anaplasia", "Hiperplasia"], 0,
         "Metaplasia é a alteração adaptativa reversível do fenótipo celular em resposta a agressão crônica."),
        ("Neoplasias", "As neoplasias malignas de origem epitelial são denominadas genericamente de:",
         ["Carcinomas", "Sarcomas", "Linfomas", "Adenomas"], 0,
         "Tumores malignos derivados de tecidos epiteliais chamam-se carcinomas; os de origem mesenquimal chamam-se sarcomas."),
        ("Distúrbios Hemodinâmicos", "A Tríade de Virchow predisponente à formação de trombos intravasculares é composta por:",
         ["Lesão endotelial, estase/turbulência do fluxo e hipercoagulabilidade", "Hipertensão, hipoxia e hiperglicemia", "Vasodilatação, exsudação e dor", "Febre, leucocitose e taquicardia"], 0,
         "A Tríade de Virchow reúne os três fatores patogênicos centrais na trombogênese: lesão endotelial, alteração do fluxo e hipercoagulabilidade."),
        ("Patologia Cardiovascular", "A aterosclerose é uma doença inflamatória crônica das artérias de médio e grande calibre iniciada por:",
         ["Disfunção endotelial e acúmulo de lipoproteínas (LDL) na túnica íntima", "Infecção fúngica da túnica adventícia", "Necrose fibrinóide da túnica média", "Aneurisma congênito"], 0,
         "A aterogênese começa com agressão endotelial, retenção de LDL oxidado na íntima e recrutamento de monócitos/macrófagos (células espumosas)."),
        ("Patologia Hepática", "A cirrose hepática representa o estágio final de diversas agressões crônicas ao fígado, caracterizando-se por:",
         ["Fibrose difusa e formação de nódulos de regeneração", "Esteatose macrovesicular pura sem fibrose", "Necrose hemorrágica maciça sem regeneração", "Hiperplasia das vias biliares sem septos"], 0,
         "A cirrose reestrutura a arquitetura hepática em nódulos de hepatócitos circundados por septos fibrosos densos.")
    ],
    "Parasitologia": [
        ("Protozoários Intestinais", "Qual protozoário flagelado habita o duodeno e jejuno humano causando diarreia com esteatorreia e síndrome de má-absorção?",
         ["Giardia duodenalis (lamblia)", "Entamoeba histolytica", "Balantidium coli", "Cryptosporidium parvum"], 0,
         "Giardia fixa-se à mucosa do delgado por seu disco ventral, atapetando a mucosa e provocando má absorção de gorduras."),
        ("Protozoários Intestinais", "A amebíase intestinal grave por Entamoeba histolytica pode causar úlceras no cólon com formato característico de:",
         ["Úlceras em 'botão de colarinho' ou 'frasco de vidro'", "Lesões em 'moeda'", "Eritema nodoso em placa", "Granulomas em roda de leme"], 0,
         "E. histolytica invade a submucosa do cólon formando úlceras de base larga e colo estreito (botão de colarinho)."),
        ("Protozoários Sanguíneos", "O agente etiológico da Doença de Chagas transmitido pelas fezes do inseto triatomíneo é o protozoário:",
         ["Trypanosoma cruzi", "Leishmania chagasi", "Plasmodium vivax", "Toxoplasma gondii"], 0,
         "T. cruzi é transmitido quando o barbeiro defeca durante o repasto sanguíneo e os tripomastigotas penetram pela picada/mucosa."),
        ("Protozoários Sanguíneos", "A malária terçã benigna caracterizada por febre a cada 48 horas e presença de hipnozoítos latentes no fígado é causada por:",
         ["Plasmodium vivax", "Plasmodium falciparum", "Plasmodium malariae", "Plasmodium ovale"], 0,
         "P. vivax forma hipnozoítos dormentes no hepatócito que causam recaídas tardias da malária terçã."),
        ("Protozoários Sanguíneos", "A Leishmaniose Visceral (Calazar) ataca o sistema fagocítico mononuclear causando hepatoesplenomegalia e anemia por infecção por:",
         ["Leishmania infantum (chagasi)", "Leishmania braziliensis", "Trypanosoma brucei", "Babesia microti"], 0,
         "L. infantum afeta fígado, baço e medula óssea, transmitida pelo mosquitos-palha (Lutzomyia longipalpis)."),
        ("Helmintos - Nematódeos", "O geohelminto Ascaris lumbricoides realiza ciclo pulmonar (Ciclo de Loss), podendo causar síndrome eosinofílica respiratória chamada:",
         ["Síndrome de Loeffler", "Síndrome de Katayama", "Síndrome de Larva Migrans Cutânea", "Doença de Romaña"], 0,
         "A migração de larvas de Ascaris pelos alvéolos pulmonares desencadeia tosse, broncoespasmo e eosinofilia (Síndrome de Loeffler)."),
        ("Helmintos - Nematódeos", "A ancilostomíase (Ancylostoma duodenale e Necator americanus) causa anemia ferropriva crônica devido a:",
         ["Fixação de vermes adultos à mucosa do delgado com hematofagia ativa", "Mapeamento e necrose da medula óssea", "Hemólise intravascular autoimune", "Destruição direta de eritrócitos na circulação"], 0,
         "Os ancilostomídeos possuem dentes/placas cortantes e sugam sangue da mucosa intestinal, gerando anemia microcítica e hipocrômica."),
        ("Helmintos - Nematódeos", "O diagnóstico parasitológico da enterobíase (Enterobius vermicularis) com prurido anal noturno é feito preferencialmente por:",
         ["Método da fita gomada (Método de Graham)", "Exame de fezes por sedimentação espontânea (Lutz)", "Hemocultura para microfilárias", "Reação de PCR no soro"], 0,
         "A fêmea de Enterobius migra à região perianal à noite para ovipor; a fita gomada recupera os ovos característicos."),
        ("Helmintos - Cestódeos", "A ingestão acidental de ovos de Taenia solium em alimentos contaminados pode levar ao desenvolvimento humano de:",
         ["Neurocisticercose", "Teníase adulta intestinal pura", "Ancilostomíase", "Hidatidose hepática"], 0,
         "Ingerir o cisto (cisticerco na carne de porco) dá teníase. Ingerir os OVOS diretamente dá cisticercose tecidual/cerebral."),
        ("Helmintos - Trematódeos", "A febre de Katayama e a hipertensão portal com fibrose periportal de Symmers são complicações da infecção por:",
         ["Schistosoma mansoni", "Fasciola hepatica", "Paragonimus westermani", "Echinococcus granulosus"], 0,
         "O Schistosoma mansoni vive no sistema porta e seus ovos nos sinusóides hepáticos provocam granulomas e fibrose periportal.")
    ],
    "Semiologia": [
        ("Ausculta Cardíaca", "O primeiro ruído cardíaco (B1) coincide com o início da sístole ventricular e resulta do fechamento das valvas:",
         ["Atrioventriculares (Mitral e Tricúspide)", "Semilunares (Aórtica e Pulmonar)", "Mitral e Aórtica exclusivamente", "Tricúspide e Pulmonar isoladamente"], 0,
         "B1 é produzido pelo fechamento abrupto das valvas mitral e tricúspide no início da sístole."),
        ("Ausculta Cardíaca", "A segunda bulha cardíaca (B2) é produzida no início da diástole pelo fechamento das valvas:",
         ["Aórtica e Pulmonar (semilunares)", "Mitral e Tricúspide", "Aórtica e Mitral", "Tricúspide e Aórtica"], 0,
         "B2 é decorrente do fechamento das valvas semilunares aórtica (A2) e pulmonar (P2)."),
        ("Sopros Cardíacos", "Um sopro holossistólico de alta frequência audível com maior intensidade no foco mitral e irradiação para a axila esquerda sugere:",
         ["Insuficiência mitral", "Estenose aórtica", "Estenose mitral", "Insuficiência aórtica"], 0,
         "A insuficiência mitral gera refluxo de sangue do VE para o AE durante toda a sístole, projetando sopro para a axila."),
        ("Ausculta Pulmonar", "Ruídos adventícios descontínuos, curtos e graves semelhantes ao roçar de mechas de cabelo escutados na inspiração indicam:",
         ["Estertores crepitantes (finos)", "Roncos e sibilos", "Estridor laríngeo", "Sopro tubário"], 0,
         "Estertores finos ocorrem pela abertura súbita de alvéolos colapsados por líquido/exsudato na inspiração tardia."),
        ("Exame do Abdome", "A interrupção súbita da inspiração profunda durante a palpação profunda do ponto cístico no hipocôndrio direito é o:",
         ["Sinal de Murphy (indicativo de colecistite aguda)", "Sinal de Blumberg", "Sinal de Rovsing", "Sinal de Giordano"], 0,
         "O sinal de Murphy positivo é dor à palpação do ponto cístico com parada inspiratória, clássico da colecistite aguda."),
        ("Exame do Abdome", "A dor à descompressão súbita da parede abdominal no ponto de McBurney na fossa ilíaca direita é o:",
         ["Sinal de Blumberg (indicativo de peritonite/apendicite)", "Sinal de Murphy", "Sinal de Cullen", "Sinal de Grey-Turner"], 0,
         "O sinal de Blumberg representa irritação peritoneal local por inflamação do apêndice cecal."),
        ("Exame do Abdome", "A palpação da fossa ilíaca esquerda desencadeando dor na fossa ilíaca direita devido ao deslocamento de gases no cólon é o:",
         ["Sinal de Rovsing", "Sinal do Psoas", "Sinal do Obturador", "Sinal de Dunphy"], 0,
         "O sinal de Rovsing ocorre na apendicite aguda quando a compressão retrógrada do cólon esquerdo distende o ceco inflamado."),
        ("Semiologia Vascular", "A aferição da pressão arterial pelo método auscultatório identifica o aparecimento do primeiro som de Korotkoff (Fase I) como a:",
         ["Pressão arterial sistólica (PAS)", "Pressão arterial diastólica (PAD)", "Pressão arterial média (PAM)", "Pressão de pulso"], 0,
         "O aparecimento dos sons de Korotkoff (Fase I) determina a PAS, e o abafamento/desaparecimento (Fase V) determina a PAD."),
        ("Exame Físico Geral", "A coloração amarelada da pele e mucosas decorrente da elevação da bilirrubina sérica acima de 2 a 2,5 mg/dL denomina-se:",
         ["Icterícia", "Cianose", "Palidez cutâneo-mucosa", "Eritema"], 0,
         "A icterícia fica visível clinicamente na esclera e freio da língua com bilirrubina total > 2,0-2,5 mg/dL."),
        ("Ausculta Pulmonar", "Ruídos adventícios contínuos de tom musical agudo provocados pelo estreitamento do calibre das vias aéreas inferiores são os:",
         ["Sibilos", "Estertores grossos (bolhosos)", "Atrito pleural", "Gorgolejo"], 0,
         "Sibilos resultam do broncoespasmo, edema ou secreção afunilando os bronquíolos na expiração (ex: asma e DPOC).")
    ],
    "Epidemiologia": [
        ("Medidas de Frequência", "O número de casos novos de uma doença que surgem em uma população em risco durante um período específico mede a:",
         ["Incidência", "Prevalência", "Letalidade", "Mortalidade proporcional"], 0,
         "Incidência quantifica a velocidade de surgimento de novos casos na população sob risco."),
        ("Medidas de Frequência", "A proporção do número total de casos (novos e antigos) existentes de uma doença em um ponto determinado no tempo é a:",
         ["Prevalência", "Incidência acumulada", "Densidade de incidência", "Taxa de ataque"], 0,
         "Prevalência mede a carga total da doença (casos acumulados) em um momento específico."),
        ("Delineamento de Estudos", "Um estudo epidemiológico observacional analítico que seleciona doentes (casos) e não doentes (controles) investigando retrospectivamente a exposição é o:",
         ["Estudo caso-controle", "Estudo de coorte", "Estudo transversal (inquérito)", "Ensaio clínico randomizado"], 0,
         "Estudos caso-controle partem do desfecho (doença) para investigar o passado de exposição (medida de associação = Odds Ratio)."),
        ("Delineamento de Estudos", "Um estudo que acompanha indivíduos expostos e não expostos ao longo do tempo avaliando o surgimento do desfecho é o:",
         ["Estudo de coorte (prospectivo ou retrospectivo)", "Estudo caso-controle", "Estudo ecológico", "Série de casos"], 0,
         "Estudos de coorte partem da exposição e acompanham os grupos no tempo para medir a incidência (medida de associação = Risco Relativo)."),
        ("Testes Diagnósticos", "A capacidade de um teste diagnóstico em identificar corretamente os indivíduos verdadeiramente doentes entre todos os doentes é a:",
         ["Sensibilidade", "Especificidade", "Valor preditivo positivo", "Acurácia global"], 0,
         "Sensibilidade = VP / (VP + FN). Mede a proporção de testes positivos entre os doentes reais."),
        ("Testes Diagnósticos", "A capacidade de um teste diagnóstico em identificar corretamente os indivíduos verdadeiramente sadios entre todos os não doentes é a:",
         ["Especificidade", "Sensibilidade", "Valor preditivo negativo", "Razão de verossimilhança positiva"], 0,
         "Especificidade = VN / (VN + FP). Mede a proporção de testes negativos entre os indivíduos sadios."),
        ("Testes Diagnósticos", "A probabilidade de um indivíduo com teste positivo ter realmente a doença é o:",
         ["Valor Preditivo Positivo (VPP)", "Valor Preditivo Negativo (VPN)", "Sensibilidade do teste", "Risco atribuível"], 0,
         "O VPP depende fortemente da prevalência da doença na população testada."),
        ("Medidas de Associação", "A razão entre a incidência nos expostos e a incidência nos não expostos em um estudo de coorte é o:",
         ["Risco Relativo (RR)", "Razão de Chances (Odds Ratio)", "Risco Atribuível no População", "Odds do Desfecho"], 0,
         "Risco Relativo (RR) = Incidência nos Expostos / Incidência nos Não Expostos."),
        ("Vigilância Epidemiológica", "O conjunto de ações que proporciona o conhecimento e acompanhamento de doenças para adoção de medidas de controle é a:",
         ["Vigilância epidemiológica", "Atenção terciária hospitalar", "Auditoria médica", "Acreditação sanitária"], 0,
         "A Vigilância Epidemiológica coleta, analisa e dissemina dados de saúde para intervenções coletivas em tempo oportuno."),
        ("Níveis de Prevenção", "Medidas de imunização (vacinas) e orientação nutricional populacional enquadram-se na:",
         ["Prevenção primária", "Prevenção secundária", "Prevenção terciária", "Prevenção quaternária"], 0,
         "Prevenção primária evita o aparecimento da doença, atuando sobre os fatores de risco antes do desfecho.")
    ]
}

print("Iniciando compilação do arquivo de questões...")

generated_questions = []

for subject_name in SUBJECTS:
    clean_id = get_clean_subject_id(subject_name)
    templates = QUESTION_TEMPLATES[subject_name]
    
    q_counter = 1
    # We will expand each core template into 10 distinct, beautifully contextualized questions per subject = 100 questions per subject
    for i in range(100):
        tmpl_idx = i % len(templates)
        sub_topic, base_q, opts, ans, exp = templates[tmpl_idx]
        intro = CLINICAL_INTROS[i % len(CLINICAL_INTROS)]
        
        var_num = (i // len(templates)) + 1
        text = f"{intro} (Caso #{i+1}).\n\n{base_q}"
        
        q_obj = {
            "id": f"basico_{clean_id}_q{q_counter}",
            "cycle": "Ciclo Básico",
            "subject": subject_name,
            "subSubject": sub_topic,
            "banca": "Trilha Estudante",
            "year": 2026 - (i % 5),
            "text": text,
            "options": opts,
            "correctIndex": ans,
            "explanation": exp,
            "difficulty": "medium"
        }
        generated_questions.append(q_obj)
        q_counter += 1

print(f"Total de questões geradas para o Ciclo Básico: {len(generated_questions)}")

# Write directly to src/basico_questions.ts
ts_content = f"""export interface Question {{
  id: string;
  cycle: string;
  subject: string;
  subSubject: string;
  banca: string;
  year: number;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
}}

export const BASICO_QUESTIONS: Question[] = {json.dumps(generated_questions, ensure_ascii=False, indent=2)};
"""

with open("src/basico_questions.ts", "w", encoding="utf-8") as f:
    f.write(ts_content)

print("src/basico_questions.ts gerado com sucesso!")
