// UFSC (SC) - Residência Médica R3 Cirurgia - 2010 (40 questões)
// Fonte: provaderesidencia.com.br (prova + gabarito oficial).
// correctIndex segue o gabarito oficial (A=0, B=1, C=2, D=3, E=4).

export const UFSC_2010_R3_CIRURGIA_QUESTIONS: any[] = [
  { id: 'ufsc_2010_r3_001', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Das alternativas abaixo, assinale a que mais sugere o diagnóstico de abdome agudo obstrutivo:',
    options: ['Vômitos, febre e leucocitose.', 'Dor contínua, tontura e vômitos.', 'Distensão abdominal, dor em cólica, antecedente de cirurgia no abdome.', 'Distensão abdominal, febre, dor contínua e vômitos.', 'Sinais de irritação peritoneal, hipotensão e taquicardia.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_002', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Em relação ao suporte nutricional do paciente cirúrgico, é correto afirmar:',
    options: ['Idade, sexo, peso e altura são variáveis consideradas no cálculo do gasto energético basal.', 'Somente os pacientes com perda ponderal acima de 10% do peso usual são candidatos a suporte nutricional parenteral.', 'Na pancreatite aguda grave, a nutrição parenteral deve ser considerada precocemente, para evitar atrofia dos enterócitos.', 'Após esofagectomia, está indicado suporte nutricional apenas nos casos de fístula da anastomose.', 'Nos casos de fístula intestinal, prefere-se a nutrição enteral para evitar translocação bacteriana.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_003', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Em casos de obstrução intestinal alta, quais dos distúrbios hidroeletrolíticos abaixo são mais frequentes?',
    options: ['Hipocalcemia e hiponatremia.', 'Hipernatremia e hipocalcemia.', 'Hiperidratação e hipomagnesemia.', 'Desidratação e hipopotassemia.', 'Desidratação e hiponatremia.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_004', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Enquanto a incidência do Câncer de Esôfago na China é de 240 casos/ano por 100 mil habitantes, no Brasil é de:',
    options: ['7 casos/ano por 100 mil habitantes.', '30 casos/ano por 100 mil habitantes.', '80 casos/ano por 100 mil habitantes.', '120 casos/ano por 100 mil habitantes.', '150 casos/ano por 100 mil habitantes.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_005', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Hérnia interna pelo espaço de Petersen tem maior incidência após:',
    options: ['gastro-jejunoanastomose pré-cólica em gastrectomia parcial por úlcera péptica.', 'gastro-jejunoanastomose pré-cólica em cirurgia bariátrica.', 'gastro-jejunoanastomose pré-cólica em gastrectomia sub-total por câncer gástrico.', 'colecisto-jejunoanastomose pré-cólica por CA de pâncreas em estádio avançado.', 'hepático-jejunoanastomose pré-cólica por estenose das vias biliares.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_006', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'A dosagem da alfafetoproteína (AFP) praticamente confirma o diagnóstico de hepatocarcinoma quando está acima de:',
    options: ['50 ng/ml.', '90 ng/ml.', '100 ng/ml.', '120 ng/ml.', '200 ng/ml.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_007', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Com relação aos cistos no mesentério, no omento e no retroperitônio, assinale a alternativa correta:',
    options: ['Em crianças, são mais frequentes antes dos 02 anos.', 'Os cistos do retroperitônio representam 25% das lesões císticas abdominais.', 'A marsupialização é sempre recomendável para esses tipos de cistos.', 'Cistos mesentéricos são mais frequentes e localizam-se principalmente no mesentério do íleo terminal.', 'Todos esses cistos são lesões relativamente frequentes e podem ocorrer em qualquer idade.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_008', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Dentre as complicações pós-transplante hepático, a menos frequente é:',
    options: ['complicações biliares.', 'episódios de rejeições agudas e crônicas.', 'obstrução da veia cava inferior.', 'hemorragia intra-abdominal.', 'estenose da artéria hepática.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_009', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Na investigação do trauma abdominal, a laparoscopia é mais bem indicada no caso de:',
    options: ['gestação.', 'hipertensão intracraniana.', 'pneumotórax hipertensivo.', 'instabilidade hemodinâmica.', 'diminuição do período de observação clínica em casos duvidosos.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_010', banca: 'UFSC', cycle: 'Internato', subject: 'Urgência e Emergência',
    text: 'No paciente politraumatizado, é indicação absoluta de toracotomia na sala de emergência:',
    options: ['parada cardíaca no hospital em doente com trauma fechado de tórax.', 'assistolia à admissão hospitalar não relacionada a tamponamento cardíaco.', 'ausência de sinais vitais no local do acidente.', 'doente com suspeita de tamponamento cardíaco com pressão sistólica menor que 60 mmHg e bradicardia.', 'idade avançada.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_011', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Na cirurgia do trauma hepático, a realização de uma "mesh wrapping" significa:',
    options: ['tamponamento do fígado com compressas.', 'oclusão das lesões com epíplon pediculado.', 'envolvimento do lobo hepático com tela absorvível e fixação da mesma para comprimir lesões hepáticas.', 'hepatectomia com ligadura dos vasos sangrantes.', 'hepatorrafia e cola de fibrina.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_012', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Com relação às lesões traumáticas do esôfago, é correta a alternativa:',
    options: ['o tórax sempre deve ser drenado.', 'nas lesões penetrantes do pescoço, o esôfago é atingido em torno de 4% dos casos.', 'o trauma contuso é mais comum que o penetrante como causa de lesão esofágica.', 'o esôfago abdominal é o mais atingido.', 'a evolução das lesões esofágicas cervicais é mais grave que as torácicas.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_013', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Com relação à síndrome de Budd-Chiari, assinale a alternativa verdadeira:',
    options: ['Pode estar associada à policitemia vera.', 'O anticoncepcional oral não é um fator de risco.', 'O parênquima hepático é largamente atingido por fibrose.', 'A radiografia simples de abdome não mostra alterações.', 'Não acarreta hipertensão portal.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_014', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Com relação ao íleo biliar, podemos afirmar que:',
    options: ['A mortalidade é em torno de 5%.', 'Os homens são os mais acometidos.', 'A idade média de acometimento é 70 anos.', 'Raramente temos obstrução intestinal.', 'No tratamento inicial, a vesícula biliar sempre é retirada.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_015', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Na pneumatose cística intestinal, é correto afirmar:',
    options: ['O cólon não é acometido.', 'O mesentério sempre está preservado.', 'A sintomatologia é grande e específica.', 'Na maioria dos casos ela é primária e não secundária.', 'Uma causa é a doença pulmonar obstrutiva crônica.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_016', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'É correto afirmar sobre a oclusão mesentérica aguda:',
    options: ['A mortalidade é de no máximo 15%.', 'A dor abdominal é severa e localizada.', 'Sangue nas fezes surge precocemente.', 'A ingestão de cocaína é uma das causas.', 'A radiografia simples de abdome diagnostica pelo menos 50% dos casos.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_017', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Na anomalia da junção bílio-pancreática, é correto afirmar:',
    options: ['É mais comum no Chile.', 'Acomete de 5-8% das pessoas.', 'Ela é um fator protetor para câncer de vesícula.', 'A colecistectomia não faz parte do seu tratamento.', 'Ocorre quando o canal comum entre a via biliar e o ducto pancreático principal é maior que 15 mm.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_018', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Nas verminoses da via biliar, é correto afirmar:',
    options: ['A clonorquíase é mais comum nas Américas.', 'Na equinococose, podemos ter obstrução completa da árvore biliar.', 'O Ascaris lumbricoides é o segundo helminto mais comum do homem.', 'Na ascaridíase bílio-pancreática, a colangite é o sintoma mais comum.', 'Na fasciolíase, os vermes atingem a árvore biliar através da papila duodenal.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_019', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'O antígeno carcinoembrionário (CEA) é usado em câncer colorretal com o objetivo de:',
    options: ['Realizar diagnóstico de câncer.', 'Realizar rastreamento populacional para câncer colônico.', 'Sugerir recidivas em paciente tratado por câncer.', 'Sugerir diferença entre patologia benigna e maligna.', 'Não ocorrer em doença benigna, fumantes etc.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_020', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Paciente masculino, 65 anos, foi submetido a retirada colonoscópica de pólipo séssil, com 1,5 cm de diâmetro, de cólon sigmoide. O exame anatomopatológico mostrou adenoma túbulo-viloso com áreas de adenocarcinoma moderadamente diferenciado que atinge a mucosa e, em 10% da lesão, a submucosa. Qual a conduta?',
    options: ['Observação e colonoscopias anuais.', 'Observação e colonoscopias semestrais.', 'Sigmoidectomia se houver recidiva da lesão.', 'Sigmoidectomia e esvaziamento ganglionar.', 'Mucosectomia colonoscópica da área afetada.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_021', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Considere um paciente, 18 anos, com trauma perfurante de reto, por PAF há 2 horas, sem outras lesões associadas, localizado a 12 cm da margem anal. Qual a conduta cirúrgica?',
    options: ['Ráfia primária.', 'Cirurgia de Hartmann.', 'Colostomia em sigmoide.', 'Colostomia em sigmoide, drenagem pré-sacra, lavagem do segmento distal (sigmoide e reto) com soro fisiológico, saindo pelo canal anal.', 'Ráfia primária e estoma de proteção.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_022', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Quando há discromia pós-queimadura significa que:',
    options: ['Houve destruição do melanócito.', 'A espessura da cicatriz bloqueia a luz e a pigmentação.', 'A isquemia final é a responsável pela hipocromia.', 'Houve fixação de pigmentos no citoplasma do histiócito.', 'A descamação repetida provoca a proliferação de fibroblasto e há consequente hiperpigmentação.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_023', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Na queimadura por gases aquecidos, o fenômeno da respiração fica prejudicado:',
    options: ['Pelo edema da árvore brônquica e lábio.', 'Pelo edema da glote e pela obstrução nasal.', 'Pelo edema da parede e interstício alveolar.', 'Pelo déficit circulatório em razão da perda de plasma.', 'Pela falta de filtração renal e alta concentração de catabólitos.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_024', banca: 'UFSC', cycle: 'Ciclo Clínico', subject: 'Dermatologia',
    text: 'Tipo de carcinoma basocelular mais propenso a dar metástases linfonodais:',
    options: ['Ulcerado.', 'Superficial.', 'Pigmentado.', 'Basoescamoso.', 'Nódulo-ulcerado.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_025', banca: 'UFSC', cycle: 'Internato', subject: 'Urologia',
    text: 'Em relação aos tumores de células germinativas do testículo, assinale a alternativa correta:',
    options: ['Cerca de 30% dos seminomas são clinicamente confinados ao testículo.', 'Cerca de 30% dos tumores não seminomatosos se apresentam como doença metastática reconhecida.', 'A radioterapia é a forma de tratamento mais amplamente aceita após a orquiectomia inguinal nos tumores não seminomatosos.', 'A linfadenectomia retroperitoneal é a modalidade de tratamento mais usada nos tumores seminomatosos após a orquiectomia inguinal.', 'Diagnóstico histológico é o fator mais importante na história natural da neoplasia testicular.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_026', banca: 'UFSC', cycle: 'Internato', subject: 'Urologia',
    text: 'O processo de lise da ureia por bactérias fornece um meio urinário alcalino e concentrações suficientes de carbonato e amônia para induzir a formação de cálculos infectivos. Assinale qual grupo de bactérias apresenta maior capacidade de desdobrar a ureia:',
    options: ['Proteus, Klebsiella, Pseudomonas e Stafilococcus.', 'Proteus, Klebsiella, Pseudomonas e E. coli.', 'Proteus, Klebsiella, E. coli e Stafilococcus.', 'Proteus, E. coli, Pseudomonas e Stafilococcus.', 'E. coli, Klebsiella, Pseudomonas e Stafilococcus.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_027', banca: 'UFSC', cycle: 'Internato', subject: 'Urologia',
    text: 'A hiperplasia prostática benigna (HPB) deve-se à hiperplasia estromatoglandular e é condição muito frequente em homens com mais de 50 anos. Com relação ao tema, assinale a alternativa correta:',
    options: ['O desenvolvimento da HPB não requer a presença intacta de uma série de reações mantidas pelos andrógenos, mas os andrógenos causam a doença.', 'O desenvolvimento da HPB requer a presença intacta de uma série de reações mantidas pelos andrógenos, mas os andrógenos não causam a doença.', 'O desenvolvimento da HPB independe dos andrógenos.', 'O desenvolvimento da HPB requer a presença intacta de uma série de reações mantidas pelos andrógenos, e os andrógenos causam a doença.', 'O desenvolvimento da HPB não requer a presença intacta de uma série de reações mantidas pelos andrógenos, mas os andrógenos não causam a doença.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_028', banca: 'UFSC', cycle: 'Ciclo Clínico', subject: 'Clínica Cirúrgica',
    text: 'Assinale o subtipo de carcinoma brônquico que se caracteriza por apresentar crescimento na parede das vias aéreas distais (lepidic growth), preservando a arquitetura pulmonar, fazendo por vezes diagnóstico diferencial com pneumonia.',
    options: ['Adenocarcinoma metastático.', 'Carcinoma espinocelular.', 'Carcinoma de células grandes.', 'Carcinoma de células pequenas.', 'Carcinoma bronquioloalveolar.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_029', banca: 'UFSC', cycle: 'Ciclo Clínico', subject: 'Clínica Cirúrgica',
    text: 'Paciente de 50 anos, masculino, com dor torácica à direita, astenia, anorexia e emagrecimento. A tomografia mostra massa em mediastino anterior, tocando a parede anterior do tórax, de 10 cm de diâmetro, limites imprecisos, circundando o tronco braquiocefálico venoso em mais de 270 graus e com desaparecimento dos planos de clivagem do mediastino. Qual a principal hipótese diagnóstica e o primeiro procedimento a ser realizado?',
    options: ['Timoma grau I, biópsia excisional.', 'Timoma invasivo, biópsia com agulha lancetante orientada por tomografia computadorizada.', 'Teratoma, biópsia excisional (cirurgia com retirada de toda a massa).', 'Tumor de células germinativas tipo seminoma, biópsia excisional.', 'Linfoma, videocirurgia com biópsia e se possível ressecção total da massa.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_030', banca: 'UFSC', cycle: 'Ciclo Clínico', subject: 'Clínica Cirúrgica',
    text: 'Paciente de 55 anos, masculino, grande fumante há mais de 20 anos e sem história prévia de neoplasia. Exame radiológico evidenciou nódulo pulmonar solitário, com as seguintes características na tomografia: 2,5 cm de diâmetro, na medular, bordos irregulares, presença de calcificação periférica e ganho de 25 UH com a injeção de contraste. Qual a melhor conduta a ser adotada?',
    options: ['Observação e nova TC em três meses.', 'Lobectomia e linfadenectomia mediastinal.', 'Segmentectomia e biópsia de congelação que, se positiva para malignidade, indica lobectomia e linfadenectomia mediastinal.', 'Punção pulmonar transparietal e, se esta for negativa, observação.', 'Videotoracoscopia e realização de segmentectomia.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_031', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Vascular',
    text: 'Com relação à úlcera de perna hipertensiva ou úlcera de Martorell, é correto afirmar que:',
    options: ['Tem como base a lesão arterial por aterosclerose.', 'A dor melhora quando o paciente deita em posição de Trendelemburg.', 'O tratamento ideal para cura da úlcera é o enxerto livre de pele.', 'A simpatectomia lombar leva à cicatrização e cura definitiva da úlcera.', 'Ocorre, preferencialmente, na face lateral da perna de mulheres hipertensas.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_032', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Vascular',
    text: 'O local mais comum de localização de êmbolos nas obstruções arteriais agudas é:',
    options: ['Bifurcação da braquial.', 'Bifurcação da artéria ilíaca.', 'Bifurcação da artéria femoral comum.', 'Artéria femoral superficial ao nível do canal dos adutores.', 'Artéria poplítea ao nível da interlinha articular do joelho.'], correctIndex: 2 },
  { id: 'ufsc_2010_r3_033', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Vascular',
    text: 'Com relação à semiologia vascular, assinale a alternativa correta:',
    options: ['O endotélio do capilar linfático é semelhante ao do capilar venoso.', 'Vasoconstrição com hiperidrose é sinal de hiperatividade simpática.', 'Rubor cutâneo com diminuição da temperatura indica circulação colateral eficiente.', 'Cianose intermitente é sinal de inviabilidade tissular.', 'O aumento no tempo de enchimento venoso traduz um déficit de circulação venosa.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_034', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Qual o indicador mais sensível que nos possibilita suspeitarmos da existência de fístula no pós-operatório imediato de gastroplastia com by-pass gástrico laparoscópico para o tratamento da obesidade mórbida?',
    options: ['febre', 'oligúria', 'leucocitose', 'taquicardia', 'dor abdominal'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_035', banca: 'UFSC', cycle: 'Ciclo Clínico', subject: 'Gastroenterologia',
    text: 'Acredita-se que a infecção pelo H. pylori desempenhe importante papel na patogênese de todas as seguintes patologias, exceto:',
    options: ['esofagite de refluxo.', 'úlcera duodenal.', 'linfoma gástrico.', 'úlcera gástrica.', 'adenocarcinoma gástrico.'], correctIndex: 0 },
  { id: 'ufsc_2010_r3_036', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Uma paciente, 30 anos, portadora de úlcera péptica recorrente apresenta elevados índices séricos de gastrina. O mais provável local do tumor é:',
    options: ['fígado.', 'pâncreas.', 'estômago.', 'duodeno.', 'linfonodo.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_037', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Indique o melhor exame para confirmar a presença de necrose pancreática infectada na pancreatite aguda:',
    options: ['Endoultrassonografia.', 'Ultrassom de abdome.', 'Tomografia computadorizada de abdome.', 'Elevação dos níveis séricos da lipase na segunda semana.', 'Punção percutânea por agulha.'], correctIndex: 4 },
  { id: 'ufsc_2010_r3_038', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'A bactéria mais comumente identificada na sepse de origem no trato biliar é:',
    options: ['Enterococos.', 'Escherichia coli.', 'Bacteroides fragilis.', 'Enterobacter fragilis.', 'Estafilococos coagulase-negativo.'], correctIndex: 1 },
  { id: 'ufsc_2010_r3_039', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'A anomalia mais frequentemente encontrada durante a dissecção inicial do pilar diafragmático para a realização da fundoplicatura laparoscópica (Nissen) é:',
    options: ['Artéria frênica inferior direita.', 'Artéria hepática comum anômala.', 'Artéria hepática direita aberrante.', 'Artéria hepática esquerda aberrante.', 'Bifurcação proximal da artéria hepática comum.'], correctIndex: 3 },
  { id: 'ufsc_2010_r3_040', banca: 'UFSC', cycle: 'Internato', subject: 'Cirurgia Geral',
    text: 'Durante a realização de colecistectomia laparoscópica numa paciente de 40 anos, a colangiografia intraoperatória identificou a presença de litíase com 6 mm de diâmetro no interior do colédoco. A melhor maneira para resolver essa situação é:',
    options: ['Exploração laparoscópica transcística do colédoco.', 'Exploração do colédoco após conversão para laparotomia.', 'Exploração laparoscópica do colédoco através de coledocotomia.', 'Litotripsia pós-operatória.', 'Observação.'], correctIndex: 0 },
];
